dish_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("dishops.urls", namespace="dishops")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dishops/urls.py
from django.contrib.admin import register
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import (
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    CookExperienceUpdateView,
    CookDeleteView,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    CookListView,
    CookDetailView,
    CookCreateView,
    UserLoginView,
    logout_view,
    UserPasswordResetConfirmView,
    UserPasswordResetView,
    UserPasswordChangeView,
    IndexView,
    ToggleAssignToDishView,
)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path(
        "dish_types/",
        DishTypeListView.as_view(),
        name="dish_type_list",
    ),
    path(
        "dish_types/create/",
        DishTypeCreateView.as_view(),
        name="dish_type_create",
    ),
    path(
        "dish_types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish_type_update",
    ),
    path(
        "dish_types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish_type_delete",
    ),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path(
        "dishes/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update"
    ),
    path(
        "dishes/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete"
    ),
    path(
        "dish/<int:pk>/toggle-assign/",
        ToggleAssignToDishView.as_view(),
        name="toggle-assign-to-dish"
    ),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path(
        "cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"
    ),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path(
        "cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"
    ),
    path("cook/create/", CookCreateView.as_view(), name="cook-create"),

    path(
        "cooks/<int:pk>/update/",
        CookExperienceUpdateView.as_view(),
        name="cook-update",
    ),
    path(
        "cooks/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete"
    ),


    path('accounts/login/', UserLoginView.as_view(), name='login'),
    path('accounts/register/', register, name='register'),
    path('accounts/logout/', logout_view, name='logout'),
    path(
        'accounts/password-change/',
        UserPasswordChangeView.as_view(),
        name='password_change'
    ),
    path(
        'accounts/password-change-done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='accounts/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'accounts/password-reset/',
        UserPasswordResetView.as_view(),
        name='password_reset'
    ),
    path(
        'accounts/password-reset-done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='accounts/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'accounts/password-reset-confirm/<uidb64>/<token>/',
        UserPasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'accounts/password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

app_name = "dishops"

dishops/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class DishType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}"


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(default=0)

    class Meta:
        verbose_name = "cook"
        verbose_name_plural = "cooks"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("dishops:cook-detail", kwargs={"pk": self.pk})


class Dish(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE)
    cooks = models.ManyToManyField(Cook, related_name="dishes", blank=True)

    def __str__(self):
        return self.name

dishops/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import (
    UserCreationForm,
    PasswordChangeForm,
    SetPasswordForm,
    PasswordResetForm,
    AuthenticationForm,
    UsernameField,
)

from django.core.exceptions import ValidationError

from dishops.models import Dish, Cook


def validate_years_of_experience(years_of_experience):
    if years_of_experience <= 0:
        raise ValidationError("Years of experience must be greater than 0.")
    if years_of_experience > 100:
        raise ValidationError(
            "Years of experience must be less than or equal to 100."
        )
    return years_of_experience


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Dish
        fields = "__all__"


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
        )

    def clean_years_of_experience(self):
        return validate_years_of_experience(
            self.cleaned_data["years_of_experience"]
        )


class CookExperienceUpdateForm(forms.ModelForm):
    class Meta:
        model = Cook
        fields = ["first_name", "last_name", "years_of_experience"]

    def clean_years_of_experience(self):
        return validate_years_of_experience(
            self.cleaned_data["years_of_experience"]
        )


class CookSearchForm(forms.Form):
    username = forms.CharField(
        max_length=50,
        required=True,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by username",
            }
        )
    )


class DishSearchForm(forms.Form):
    dish_type = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by dish type",
            }
        )
    )


class DishTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by name",
            }
        )
    )


class UserLoginForm(AuthenticationForm):
    username = UsernameField(
        widget=forms.TextInput(
            attrs={"class": "form-control form-control-lg",
                   "placeholder": "Username"}
        )
    )
    password = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(
            attrs={"class": "form-control form-control-lg",
                   "placeholder": "Password"}
        ),
    )


class UserPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control form-control-lg',
        'placeholder': 'Email'
    }))


class UserSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(
        max_length=50,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control form-control-lg',
                'placeholder': 'New Password'
            }
        ),
        label="New Password"
    )

    new_password2 = forms.CharField(
        max_length=50,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control form-control-lg',
                'placeholder': 'Confirm New Password'
            }
        ),
        label="Confirm New Password"
    )


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        max_length=50,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control form-control-lg',
                'placeholder': 'Old Password'
            }
        ),
        label="Old Password"
    )

    new_password1 = forms.CharField(
        max_length=50,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control form-control-lg',
                'placeholder': 'New Password'
            }
        ),
        label="New Password"
    )

    new_password2 = forms.CharField(
        max_length=50,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control form-control-lg',
                'placeholder': 'Confirm New Password'
            }
        ),
        label="Confirm New Password"
    )

dishops/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import (
    LoginView,
    PasswordResetView,
    PasswordResetConfirmView,
    PasswordChangeView
)
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

from dishops.models import Cook, Dish, DishType
from dishops.forms import (
    DishTypeSearchForm,
    DishSearchForm,
    DishForm,
    CookExperienceUpdateForm,
    CookCreationForm,
    CookSearchForm,
    UserPasswordResetForm,
    UserSetPasswordForm,
    UserPasswordChangeForm,
)


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = "dishops/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["num_cooks"] = Cook.objects.count()
        context["num_dishes"] = Dish.objects.count()
        context["num_dish_types"] = DishType.objects.count()

        num_visits = self.request.session.get("num_visits", 0)
        self.request.session["num_visits"] = num_visits + 1
        context["num_visits"] = num_visits + 1

        return context


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    context_object_name = "dish_type_list"
    template_name = "dishops/dish_type_list.html"
    paginate_by = 5

    queryset = DishType.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishTypeSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        name = self.request.GET.get("name")
        if name:
            return self.queryset.filter(name__icontains=name)
        return self.queryset


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("dishops:dish_type_list")


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("dishops:dish_type_list")


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    success_url = reverse_lazy("dishops:dish_type_list")


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    template_name = "dishops/dish_list.html"
    paginate_by = 5
    queryset = Dish.objects.select_related("dish_type")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)
        dish_type = self.request.GET.get("dish_type", "")
        context["search_form"] = DishSearchForm(
            initial={"dish_type": dish_type}
        )
        return context

    def get_queryset(self):
        dish_type = self.request.GET.get("dish_type")
        if dish_type:
            return self.queryset.filter(dish_type__name__icontains=dish_type)
        return self.queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish
    template_name = "dishops/dish_detail.html"


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("dishops:dish-list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("dishops:dish-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("dishops:dish-list")


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    queryset = Cook.objects.all()
    template_name = "dishops/cook_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = CookSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        username = self.request.GET.get("username")

        if username:
            return self.queryset.filter(username__icontains=username)
        return self.queryset


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    template_name = "dishops/cook_detail.html"
    queryset = Cook.objects.all().prefetch_related("dishes__dish_type")


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    template_name = "dishops/cook_form.html"
    form_class = CookCreationForm


class UserLoginView(LoginView):
    template_name = 'accounts/sign-in.html'
    form_class = AuthenticationForm


def logout_view(request):
    logout(request)
    return redirect('/accounts/login')


class CookExperienceUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookExperienceUpdateForm
    success_url = reverse_lazy("dishops:cook-list")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("dishops:cook-list")


class ToggleAssignToDishView(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        cook = Cook.objects.get(id=request.user.id)
        dish = Dish.objects.get(id=pk)

        if dish in cook.dishes.all():
            cook.dishes.remove(pk)
        else:
            cook.dishes.add(pk)
        return HttpResponseRedirect(reverse_lazy("dishops:dish-detail", args=[pk]))


class UserPasswordResetView(PasswordResetView):
    template_name = 'accounts/password_reset.html'
    form_class = UserPasswordResetForm


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'
    form_class = UserSetPasswordForm


class UserPasswordChangeView(PasswordChangeView):
    template_name = 'accounts/password_change.html'
    form_class = UserPasswordChangeForm

templates/dishops/cook_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Cook</title>
{% endblock %}

{% block body %}{% endblock body %}

{% block header %}
{% include 'includes/sidebar.html' %}
{% endblock header %}

{% block content %}
<!-- -------- START HEADER 8 w/ card over right bg image ------- -->
<header>
  <div class="page-header min-vh-85">
    <div>
      <img
          class="position-absolute fixed-top ms-auto w-50 h-100 z-index-0 d-none d-sm-none d-md-block border-radius-section border-top-end-radius-0 border-top-start-radius-0 border-bottom-end-radius-0"
          src="{% static 'img/curved-images/curved8.jpg' %}" alt="image">
    </div>
    <div class="container mt-5">
      <div class="row">
        <div class="col-lg-7 d-flex justify-content-center flex-column">
          <div class="card d-flex blur justify-content-center p-4 shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
            <div class="text-center">
              <h3>
                Username: {{ cook.username }}
              </h3>
            </div>
            <div class="cook-details text-left ms-3">
              <p class="mb-0"><strong>First name:</strong> {{ cook.first_name }}</p>
              <p class="mb-0"><strong>Last name:</strong> {{ cook.last_name }}</p>
              <p class="mb-0"><strong>Years of experience:</strong> {{ cook.years_of_experience }}</p>
              <p class="mb-0"><strong>Is staff:</strong> {{ cook.is_staff }}</p>
            </div>
            <div class="ml-3 mt-3 ms-3">
              <h4>Dishes prepared by this cook:</h4>
              {% for dish in cook.dishes.all %}
              <p class="mb-0"><strong>Name:</strong> {{ dish.name }}</p>
              <p class="mb-0"><strong>Dish type:</strong> {{ dish.dish_type.name }}</p>
              <p class="text-muted mb-0"><strong>Id:</strong> {{dish.id}}</p>

              {% empty %}
              <p>No dishes!</p>
              {% endfor %}
            </div>


            <div class="row justify-space-between text-center py-2">
              <div class="col-12 mx-auto">
                <a href="{% url 'dishops:cook-update' pk=cook.id %}"
                   class="btn bg-gradient-light w-auto me-3">
                  Update
                </a>
                <a href="{% url 'dishops:cook-delete' pk=cook.id %}"
                   class="btn bg-gradient-primary link-to-page">
                  Delete
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock content %}

templates/dishops/cook_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Cook List</title>
{% endblock %}

{% block body %}{% endblock body %}

{% block header %}
{% include 'includes/sidebar_light.html' %}
{% endblock header %}

{% block content %}
<header>
  <div class="page-header min-vh-85">
    <div>
      <img
          class="position-absolute fixed-top ms-auto w-50 h-100 z-index-0 d-none d-sm-none d-md-block border-radius-section border-top-end-radius-0 border-top-start-radius-0 border-bottom-end-radius-0"
          src="{% static 'img/curved-images/curved8.jpg' %}" alt="image">
    </div>
    <div class="container-fluid mt-5">
      <div class="row">
        <div class="col-lg-7 mx-auto d-flex justify-content-center flex-column">
          <div class="card d-flex blur justify-content-center p-4 shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
            <div class="text-center">
              <h3>Cook List</h3>
            </div>
            <div class="mt-4">
              {% if cook_list %}
              <table class="table">
                <thead>
                <tr>
                  <th style="color: #333;">ID</th>
                  <th style="color: #333;">Username</th>
                  <th style="color: #333;">First name</th>
                  <th style="color: #333;">Last name</th>
                  <th style="color: #333;">Years of experience</th>
                </tr>
                </thead>
                <tbody>
                {% for cook in cook_list %}
                <tr>
                  <td>{{ cook.id }}</td>
                  <td>
                    <a href="{{ cook.get_absolute_url }}">{{ cook.username }} {% if user == cook %}(Me){% endif %}</a>
                  </td>
                  <td>{{ cook.first_name }}</td>
                  <td>{{ cook.last_name }}</td>
                  <td>{{ cook.years_of_experience }}</td>
                </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
            <div class="text-center">
              <a href="{% url 'dishops:cook-create' %}" class="btn bg-gradient-primary mt-3 mb-0">Create</a>
            </div>
          </div>
          {% else %}
          <p>There are no cooks in the service.</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</header>

{% endblock content %}

{% block javascripts %}
<script>
    // get the element to animate
    var element = document.getElementById('count-stats');
    var elementHeight = element.clientHeight;

    // listen for scroll event and call animate function

    document.addEventListener('scroll', animate);

    // check if element is in view
    function inView() {
        // get window height
        var windowHeight = window.innerHeight;
        // get number of pixels that the document is scrolled
        var scrollY = window.scrollY || window.pageYOffset;
        // get current scroll position (distance from the top of the page to the bottom of the current viewport)
        var scrollPosition = scrollY + windowHeight;
        // get element position (distance from the top of the page to the bottom of the element)
        var elementPosition = element.getBoundingClientRect().top + scrollY + elementHeight;

        // is scroll position greater than element position? (is element in view?)
        if (scrollPosition > elementPosition) {
            return true;
        }

        return false;
    }

    var animateComplete = true;

    // animate element when it is in view
    function animate() {

        // is element in view?
        if (inView()) {
            if (animateComplete) {
                if (document.getElementById('state1')) {
                    const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
                    if (!countUp.error) {
                        countUp.start();
                    } else {
                        console.error(countUp.error);
                    }
                }
                if (document.getElementById('state2')) {
                    const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
                    if (!countUp1.error) {
                        countUp1.start();
                    } else {
                        console.error(countUp1.error);
                    }
                }
                if (document.getElementById('state3')) {
                    const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
                    if (!countUp2.error) {
                        countUp2.start();
                    } else {
                        console.error(countUp2.error);
                    }
                    ;
                }
                animateComplete = false;
            }
        }
    }

    if (document.getElementById('typed')) {
        var typed = new Typed("#typed", {
            stringsElement: '#typed-strings',
            typeSpeed: 90,
            backSpeed: 90,
            backDelay: 200,
            startDelay: 500,
            loop: true
        });
    }
</script>
<script>
    if (document.getElementsByClassName('page-header')) {
        window.onscroll = debounce(function () {
            var scrollPosition = window.pageYOffset;
            var bgParallax = document.querySelector('.page-header');
            var oVal = (window.scrollY / 3);
            bgParallax.style.transform = 'translate3d(0,' + oVal + 'px,0)';
        }, 6);
    }
</script>
{% endblock javascripts %}

templates/dishops/dish_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Dish list</title>
{% endblock %}

{% block body %}{% endblock body %}

{% block header %}
{% include 'includes/sidebar.html' %}
{% endblock header %}

{% block content %}
<!-- -------- START HEADER 8 w/ card over right bg image ------- -->
<header>
  <div class="page-header min-vh-85 mt-5">
    <div>
      <img
          class="position-absolute fixed-top ms-auto w-50 h-100 z-index-0 d-none d-sm-none d-md-block border-radius-section border-top-end-radius-0 border-top-start-radius-0 border-bottom-end-radius-0"
          src="{% static 'img/curved-images/curved8.jpg' %}" alt="image">
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-7 d-flex justify-content-center flex-column">
          <div class="card d-flex blur justify-content-center p-4 shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
            <div class="text-center">
              <h3>{{ dish.name }}</h3>
            </div>
            <p class="mb-0">
              Dish type: ({{ dish.dish_type.name }})
            </p>
            <h4>
              Cooks, who prepare these dishes:
            </h4>
            <ul>
              {% for cook in dish.cooks.all %}
              <li>{{ cook.username }} ({{ cook.first_name }} {{ cook.last_name }})</li>
              {% endfor %}
            </ul>
            <div class="row justify-space-between text-center py-2">
              <div class="col-12 mx-auto">
                {% if dish in user.dishes.all %}
                <a href="{% url 'dishops:toggle-dish-assign' pk=dish.id %}" class="btn bg-gradient-light w-auto me-3">
                  Delete me from this dish
                </a>
                {% else %}
                <a href="{% url 'dishops:toggle-dish-assign' pk=dish.id %}" class="btn bg-gradient-light w-auto me-3">
                  Assign me from this dish
                </a>
                {% endif %}

                <a href="{% url 'dishops:dish-update' pk=dish.id %}"
                   class="btn bg-gradient-light w-auto me-3">Update</a>
                <a href="{% url 'dishops:dish-delete' pk=dish.id %}"
                   class="btn bg-gradient-primary link-to-page">Delete</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock content %}

templates/dishops/dish_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Dish list</title>
{% endblock %}

{% block body %}{% endblock body %}

{% block header %}
{% include 'includes/sidebar_light.html' %}
{% endblock header %}

{% block content %}
<!-- -------- START HEADER 8 w/ card over right bg image ------- -->
<header>
  <div class="page-header min-vh-85">
    <div>
      <img
          class="position-absolute fixed-top ms-auto w-50 h-100 z-index-0 d-none d-sm-none d-md-block border-radius-section border-top-end-radius-0 border-top-start-radius-0 border-bottom-end-radius-0"
          src="{% static 'img/curved-images/curved8.jpg' %}" alt="image">
    </div>
    <div class="container mt-5">
      <div class="row">
        <div class="col-lg-7 d-flex justify-content-center flex-column">
          <div class="card d-flex blur justify-content-center p-4 shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
            <div class="text-center">
              <h3>Dish list</h3>
              <p class="mb-0">
                Discover the variety of dishes available in our kitchen management system.
              </p>
            </div>
            <div class="mt-4">
              {% if dish_list %}
              <ul class="list-unstyled text-start">
                {% for dish in dish_list %}
                <li>
                  <a href="{% url 'dishops:dish-detail' pk=dish.id %}">{{ dish.name }}</a>
                  ({{ dish.dish_type.name }})
                </li>
                {% endfor %}
              </ul>
              {% else %}
              <p>There are no dishes in the kitchen management</p>
              {% endif %}

              <div class="d-flex justify-content-center">
                <a href="{% url 'dishops:dish-create' %}" class="btn bg-gradient-primary mb-3 mb-0">Create</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock content %}

templates/dishops/dish_type_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Dish types list</title>
{% endblock %}

{% block body %}{% endblock body %}

{% block header %}
{% include 'includes/sidebar_light.html' %}
{% endblock header %}

{% block content %}
<!-- -------- START HEADER 8 w/ card over right bg image ------- -->
<header>
  <div class="page-header min-vh-85">
    <div>
      <img
          class="position-absolute fixed-top ms-auto w-50 h-100 z-index-0 d-none d-sm-none d-md-block border-radius-section border-top-end-radius-0 border-top-start-radius-0 border-bottom-end-radius-0"
          src="{% static 'img/curved-images/curved8.jpg' %}" alt="image">
    </div>
    <div class="container mt-5">
      <div class="row">
        <div class="col-lg-7 d-flex justify-content-center flex-column">
          <div class="card d-flex blur justify-content-center p-4 shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
            <div class="text-center">
              <h3>Dish type List</h3>
              <p class="mb-0">
                Discover the variety of dishes available in our kitchen management system.
              </p>
            </div>
            <div class="mt-4">
              {% if dish_type_list %}
              <table class="table">
                <tr>
                  <th style="color: #333;">ID</th>
                  <th style="color: #333;">Name</th>
                  <th style="color: #333;">Update</th>
                  <th style="color: #333;">Delete</th>
                </tr>

                {% for dish_type in dish_type_list %}
                <tr>
                  <td>
                    {{ dish_type.id }}
                  </td>
                  <td>
                    {{ dish_type.name }}
                  </td>
                  <td>
                    <a href="{% url 'dishops:dish_type_update' pk=dish_type.id %}">
                      Update
                    </a>
                  </td>
                  <td>
                    <a style="color: red"
                       href="{% url 'dishops:dish_type_delete' pk=dish_type.id %}">
                      Delete
                    </a>
                  </td>
                </tr>
                {% endfor %}
              </table>

              {% else %}
              <p>There are no dish types in the kitchen.</p>
              {% endif %}
              <div class="d-flex justify-content-center">
                <a href="{% url 'dishops:dish_type_create' %}" class="btn bg-gradient-primary mb-3 mb-0">Create</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock content %}