dish_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("dishops.urls", namespace="dishops")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dishops/urls.py
from django.contrib.admin import register
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import (
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    CookExperienceUpdateView,
    CookDeleteView,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    CookListView,
    CookDetailView,
    CookCreateView,
    UserLoginView,
    logout_view,
    UserPasswordResetConfirmView,
    UserPasswordResetView,
    UserPasswordChangeView,
    IndexView,
    ToggleAssignToDishView,
)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path(
        "dish_types/",
        DishTypeListView.as_view(),
        name="dish_type_list",
    ),
    path(
        "dish_types/create/",
        DishTypeCreateView.as_view(),
        name="dish_type_create",
    ),
    path(
        "dish_types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish_type_update",
    ),
    path(
        "dish_types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish_type_delete",
    ),
    path("dishes/", DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
    path(
        "dishes/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update"
    ),
    path(
        "dishes/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete"
    ),
    path(
        "dish/<int:pk>/toggle-assign/",
        ToggleAssignToDishView.as_view(),
        name="toggle-assign-to-dish"
    ),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path(
        "cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"
    ),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path(
        "cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"
    ),
    path("cook/create/", CookCreateView.as_view(), name="cook-create"),

    path(
        "cooks/<int:pk>/update/",
        CookExperienceUpdateView.as_view(),
        name="cook-update",
    ),
    path(
        "cooks/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete"
    ),


    path('accounts/login/', UserLoginView.as_view(), name='login'),
    path('accounts/register/', register, name='register'),
    path('accounts/logout/', logout_view, name='logout'),
    path(
        'accounts/password-change/',
        UserPasswordChangeView.as_view(),
        name='password_change'
    ),
    path(
        'accounts/password-change-done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='accounts/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'accounts/password-reset/',
        UserPasswordResetView.as_view(),
        name='password_reset'
    ),
    path(
        'accounts/password-reset-done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='accounts/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'accounts/password-reset-confirm/<uidb64>/<token>/',
        UserPasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'accounts/password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

app_name = "dishops"

templates/includes/footer_background.html
<footer class="footer pt-5 mt-5" style="padding-bottom: 30px;">
  <hr class="horizontal dark mb-5">
  <div class="container">
    <div class="row">
      <div class="col-8 mx-auto text-center mt-1">
        <p class="mb-0 text-secondary">
          &copy; 2024 Boliziuk Oksana - All rights reserved. Developed with passion.
        </p>
      </div>
    </div>
  </div>
</footer>

templates/includes/footer_fullscreen.html
<footer class="footer pt-5 mt-5" style="padding-bottom: 30px;">
  <hr class="horizontal dark mb-5">
  <div class="container">
    <div class="row">
      <div class="col-8 mx-auto text-center mt-1">
        <p class="mb-0 text-secondary">
          &copy; 2024 Boliziuk Oksana - All rights reserved. Developed with passion.
        </p>
      </div>
    </div>
  </div>
</footer>

templates/includes/footer_signin.html
<footer class="footer pt-5 mt-5" style="padding-bottom: 30px;">
  <hr class="horizontal dark mb-5">
  <div class="container">
    <div class="row">
      <div class="col-8 mx-auto text-center mt-1">
        <p class="mb-0 text-secondary">
          &copy; 2024 Boliziuk Oksana - All rights reserved. Developed with passion.
        </p>
      </div>
    </div>
  </div>
</footer>

templates/includes/pagination.html
<div class="container">
  <div class="row justify-space-between py-2">
    <div class="col-lg-4 mx-auto">
      <ul class="pagination pagination-primary m-4">

        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true"><i class="fa fa-angle-double-left" aria-hidden="true"></i></span>
          </a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <span class="page-link" aria-hidden="true"><i class="fa fa-angle-double-left" aria-hidden="true"></i></span>
        </li>
        {% endif %}

        <li class="page-item active">
          <a class="page-link active" href="javascript:;" style="font-size: 12px; color: white">
            {{ page_obj.number }} of {{ paginator.num_pages }}
          </a>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true"><i class="fa fa-angle-double-right" aria-hidden="true"></i></span>
          </a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <span class="page-link" aria-hidden="true"><i class="fa fa-angle-double-right" aria-hidden="true"></i></span>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>

templates/includes/scripts.html
  {% load static %}
  
<!-- Core JS Files -->
<script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>

<!-- Plugins -->
<script src="{% static 'js/plugins/parallax.min.js' %}"></script>
<script src="{% static 'js/plugins/choices.min.js' %}"></script>
<script src="{% static 'js/plugins/countup.min.js' %}"></script>
<script src="{% static 'js/plugins/prism.min.js' %}"></script>
<script src="{% static 'js/plugins/flatpickr.min.js' %}"></script>
<script src="{% static 'js/plugins/moment.min.js' %}"></script>
<script src="{% static 'js/plugins/rellax.min.js' %}"></script>
<script src="{% static 'js/plugins/tilt.min.js' %}"></script>
<script src="{% static 'js/plugins/typedjs.js' %}"></script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>

<script src="{% static 'js/soft-design-system.min.js' %}" type="text/javascript"></script>

templates/includes/search_form.html
{% load crispy_forms_filters %}
<div class="input-group input-group-sm">
  <form method="get" action="" class="form-inline d-flex align-items-center">

    {{ search_form|crispy }}
    <input class="btn btn-light ms-2" type="submit" value="🔍">
  </form>
</div>

templates/includes/sidebar.html
{% load static %}

<!-- Navbar -->
<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav
          class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid px-0">
          <a class="navbar-brand font-weight-bolder ms-sm-3"
             href="{% url 'dishops:index' %}" rel="tooltip"
             title="Dish tracker" data-placement="bottom">
            Home
          </a>
          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse"
                  data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false"
                  aria-label="Toggle navigation">
            <span class="navbar-toggler-icon mt-2">
              <span class="navbar-toggler-bar bar1"></span>
              <span class="navbar-toggler-bar bar2"></span>
              <span class="navbar-toggler-bar bar3"></span>
            </span>
          </button>
          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
            <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
              <li class="nav-item mx-2">
                <a class="nav-link ps-2" href="{% url 'dishops:dish_type_list' %}">
                  Dish Types
                </a>
              </li>
              <li class="nav-item mx-2">
                <a class="nav-link ps-2" href="{% url 'dishops:dish-list' %}">
                  Dishes
                </a>
              </li>
              <li class="nav-item mx-2">
                <a class="nav-link ps-2" href="{% url 'dishops:cook-list' %}">
                  Cooks
                </a>
              </li>

              {% if request.user.is_authenticated %}
              <li class="nav-item ms-lg-auto">
                <a class="nav-link nav-link-icon me-2" href="{% url 'dishops:logout' %}">
                  <i class="fa fa-sign-out me-1"></i>
                  <p class="d-inline text-sm z-index-1 font-bold" data-bs-toggle="tooltip" data-bs-placement="bottom"
                     title="Logout">Logout</p>
                </a>
              </li>
              {% else %}
              <li class="nav-item ms-lg-auto">
                <a class="nav-link nav-link-icon me-2" href="{% url 'dishops:login' %}">
                  <i class="fa fa-sign-in me-1"></i>
                  <p class="d-inline text-sm z-index-1 font-bold" data-bs-toggle="tooltip" data-bs-placement="bottom"
                     title="Login">Login</p>
                </a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </div>
</div>

templates/includes/sidebar_light.html
{% load static %}

<!-- Navbar -->

<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav
          class="navbar navbar-expand-lg blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4"
          style="opacity: 0.8;">
        <div class="container-fluid px-0">
          <a class="navbar-brand font-weight-bolder ms-sm-3" href="{% url 'dishops:index' %}" rel="tooltip" title="Dish tracker"
             data-placement="bottom">
            Home
          </a>
          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse"
                  data-bs-target="#navigation"
                  aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon mt-2">
            <span class="navbar-toggler-bar bar1"></span>
            <span class="navbar-toggler-bar bar2"></span>
            <span class="navbar-toggler-bar bar3"></span>
          </span>
          </button>
          <div class="collapse navbar-collapse w-100 pt-3 pb-2 py-lg-0 ms-lg-12 ps-lg-5" id="navigation">
            <ul class="navbar-nav navbar-nav-hover w-100">
              <li class="nav-item mx-2">
                <a class="nav-link ps-2" href="{% url 'dishops:dish_type_list' %}">
                  Dish Types
                </a>
              </li>
              <li class="nav-item mx-2">
                <a class="nav-link ps-2" href="{% url 'dishops:dish-list' %}">
                  Dishes
                </a>
              </li>
              <li class="nav-item mx-2">
                <a class="nav-link ps-2" href="{% url 'dishops:cook-list' %}">
                  Cooks
                </a>
              </li>
              <li class="nav-item ms-lg-auto">
                  {% include "includes/search_form.html" %}
              </li>

              {% if request.user.is_authenticated %}
              <li class="nav-item ms-lg-auto">
                <a class="nav-link nav-link-icon me-2" href="{% url 'dishops:logout' %}">
                  <i class="fa fa-sign-out me-1"></i>
                  <p class="d-inline text-sm z-index-1 font-bold" data-bs-toggle="tooltip" data-bs-placement="bottom"
                     title="Logout">Logout</p>
                </a>
              </li>
              {% else %}
              <li class="nav-item ms-lg-auto">
                <a class="nav-link nav-link-icon me-2" href="{% url 'dishops:login' %}">
                  <i class="fa fa-sign-in me-1"></i>
                  <p class="d-inline text-sm z-index-1 font-bold" data-bs-toggle="tooltip" data-bs-placement="bottom"
                     title="Login">Login</p>
                </a>
              </li>
              {% endif %}
            </ul>
      </nav>
    </div>
  </div>
</div>